# Travis configuration file for HyperBuffer
dist: trusty
os:
 # - linux
  - osx
 # - windows
language:
  - cpp
compiler:
#  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
#      - clang
      - cmake
script:
  # Link clang and g++ to their standard commands
  - ln -s /usr/bin/g++ /usr/local/bin/g++
  # Export CXX to tell cmake which compiler to use
  - export CXX=/usr/bin/g++
  # Check versions of g++ and cmake
  - g++ -v && cmake --version
  # Run your build commands next
  - export CPP_STANDARD=14
  - cd deploy
  - mkdir -p build
  - cd build
  - cmake ../..
  - make
#  - ./HyperBufferTest
