# Travis configuration file for HyperBuffer
dist: trusty
language:
    - cpp
matrix:
    include:
        - os: osx
          osx_image: xcode11.3
          compiler: clang
          env: COMPILER='clang++'
          
        - os: linux
          dist: bionic
          compiler: gcc
          
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7']
          env: COMPILER='g++-7'
         
before_script:
    # Export CXX to tell cmake which compiler to use
    - export CXX=${COMPILER}
    - export CPP_STANDARD=14
    # Check versions
    - cmake --version
    # Run your build commands next
    - cd deploy
    - mkdir -p build
    - cd build
    - cmake -H. -j 2 ../.. -DCMAKE_BUILD_TYPE=Debug
    
script:
    - make -j 2
    #- ./HyperBufferTest
    - ctest -V -j 2

    
