name: Create/Test Single-Include Header
on:
  workflow_call:
jobs:
  check-single-include:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'  
      - name: Amalgamate Headers
        working-directory: deploy
        run: sh ./generate_single_header_include.sh
      - name: Setup & Cmake
        working-directory: deploy
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DTEST_WITH_AMALGAMATED_HEADER=Yes ../..
      - name: Build & Run Tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        working-directory: deploy/build
        run: |
          cmake --build . --parallel 2
          ctest -C ${{ matrix.build_type }} -L HyperBufferTest -j 2
      - name: Check single_include header
        run: |
          if [[ `git status --porcelain --untracked-files=no single_include/HyperBuffer.hpp` ]]; then
            echo "Single-include header needs to be updated -- please run deploy/generate_single_header_include.sh and commit the changes"
            exit -1
          else
            echo "Single-include header is up-to-date"
          fi
          
